name: Secret Scan CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    name: GitLeaks Secret Scan

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Run GitLeaks from the public Docker image
      - name: Run Gitleaks Secret Scan
        run: |
          docker run --rm \
            -v $(pwd):/app \
            zricethezav/gitleaks:latest \
            detect --source=/app --report=/app/gitleaks-scan-output.json

      # Step 3: Upload the secret scan report as an artifact
      - name: Upload Secret Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: Gitleaks Secret Scan Report
          path: gitleaks-scan-output.json
